
* Comment lines

http://orgmode.org/manual/Comment-lines.html#Comment-lines

Comment lines are editable, visible in .org and not exported.

| effective area | one line | multiple lines        | a sub-tree           |
|                |          | region                |                      |
|----------------+----------+-----------------------+----------------------|
| format         | #        | #+BEGIN_COMMENT       | * COMMENT            |
|                |          | regions to be comment |                      |
|                |          | #+END_COMMENT         |                      |
|----------------+----------+-----------------------+----------------------|
|                |          |                       | get inside a subtree |
|                |          |                       | C-c ;                |
|                |          |                       |                      |

#+BEGIN_EXAMPLE
# one line comment, will not be exported.
#+END_EXAMPLE

# one line comment, will not be exported.



#+BEGIN_EXAMPLE
#+BEGIN_COMMENT

regions 
of 
comments.

will not be 
exported.

#+END_COMMENT
#+END_EXAMPLE



#+BEGIN_COMMENT

regions 
of 
comments.

will not be 
exported.

#+END_COMMENT



** COMMENT a sub-tree for comment

C-c ;
Toggle the ‘COMMENT’ keyword at the beginning of an entry.


#+BEGIN_EXAMPLE
** COMMENT a sub-tree for comment

C-c ;
Toggle the ‘COMMENT’ keyword at the beginning of an entry.
#+END_EXAMPLE


* Paragraphs, line breaks, and quoting

http://orgmode.org/manual/Paragraphs.html#Paragraphs

| export and view in html | VERSE | QUOTE | CENTER         |
|-------------------------+-------+-------+----------------|
| keep the line breaks    | yes   | no    | no             |
|                         |       |       |                |
| indentation             | yes   | yes   | not applicable |


** VERSE

To keep the line breaks in a region, but otherwise use normal formatting.

     #+BEGIN_VERSE
      Great clouds overhead
      Tiny black birds rise and fall
      Snow covers Emacs
     
          -- AlexSchroeder
     #+END_VERSE

#+BEGIN_VERSE
Great clouds overhead
Tiny black birds rise and fall
Snow covers Emacs
     
    -- AlexSchroeder


When quoting a passage from another document, it is customary to format this as a paragraph that is indented on both the left and the right margin. You can include quotations in Org mode documents like this: When quoting a passage from another document, it is customary to format this as a paragraph that is indented on both the left and the right margin. You can include quotations in Org mode documents like this: When quoting a passage from another document, it is customary to format this as a paragraph that is indented on both the left and the right margin. You can include quotations in Org mode documents like this: When quoting a passage from another document, it is customary to format this as a paragraph that is indented on both the left and the right margin. You can include quotations in Org mode documents like this: When quoting a passage from another document, it is customary to format this as a paragraph that is indented on both the left and the right margin. You can include quotations in Org mode documents like this: When quoting a passage from another document, it is customary to format this as a paragraph that is indented on both the left and the right margin. You can include quotations in Org mode documents like this:

#+END_VERSE

#+BEGIN_VERSE

#+END_VERSE


** a QUOTE

#+BEGIN_QUOTE
Everything should be made as simple as possible,
but not any simpler -- Albert Einstein

When quoting a passage from another document, it is customary to format this as a paragraph that is indented on both the left and the right margin. You can include quotations in Org mode documents like this: When quoting a passage from another document, it is customary to format this as a paragraph that is indented on both the left and the right margin. You can include quotations in Org mode documents like this: When quoting a passage from another document, it is customary to format this as a paragraph that is indented on both the left and the right margin. You can include quotations in Org mode documents like this: When quoting a passage from another document, it is customary to format this as a paragraph that is indented on both the left and the right margin. You can include quotations in Org mode documents like this: When quoting a passage from another document, it is customary to format this as a paragraph that is indented on both the left and the right margin. You can include quotations in Org mode documents like this: When quoting a passage from another document, it is customary to format this as a paragraph that is indented on both the left and the right margin. You can include quotations in Org mode documents like this:




#+END_QUOTE


** QUOTE

#+BEGIN_QUOTE
Everything should be made as simple as possible,
but not any simpler -- Albert Einstein

When quoting a passage from another document, it is customary to format this as a paragraph that is indented on both the left and the right margin. You can include quotations in Org mode documents like this: When quoting a passage from another document, it is customary to format this as a paragraph that is indented on both the left and the right margin. You can include quotations in Org mode documents like this: When quoting a passage from another document, it is customary to format this as a paragraph that is indented on both the left and the right margin. You can include quotations in Org mode documents like this: When quoting a passage from another document, it is customary to format this as a paragraph that is indented on both the left and the right margin. You can include quotations in Org mode documents like this: When quoting a passage from another document, it is customary to format this as a paragraph that is indented on both the left and the right margin. You can include quotations in Org mode documents like this: When quoting a passage from another document, it is customary to format this as a paragraph that is indented on both the left and the right margin. You can include quotations in Org mode documents like this:




#+END_QUOTE




** CENTER

place center.

#+BEGIN_CENTER
Everything should be made as simple as possible, \\
but not any simpler

Everything should be made as simple as possible, 
but not any simpler

When quoting a passage from another document, it is customary to format this as a paragraph that is indented on both the left and the right margin. You can include quotations in Org mode documents like this: When quoting a passage from another document, it is customary to format this as a paragraph that is indented on both the left and the right margin. You can include quotations in Org mode documents like this: When quoting a passage from another document, it is customary to format this as a paragraph that is indented on both the left and the right margin. You can include quotations in Org mode documents like this: When quoting a passage from another document, it is customary to format this as a paragraph that is indented on both the left and the right margin. You can include quotations in Org mode documents like this: When quoting a passage from another document, it is customary to format this as a paragraph that is indented on both the left and the right margin. You can include quotations in Org mode documents like this: When quoting a passage from another document, it is customary to format this as a paragraph that is indented on both the left and the right margin. You can include quotations in Org mode documents like this:


#+END_CENTER


* Literal examples

http://orgmode.org/manual/Literal-examples.html



     #+BEGIN_EXAMPLE
     Some example from a text file.
     #+END_EXAMPLE

#+BEGIN_EXAMPLE -n
<
e
tab
#+END_EXAMPLE

     #+BEGIN_SRC emacs-lisp
       (defun org-xor (a b)
          "Exclusive or."
          (if a (not b) b))
     #+END_SRC

